<?xml version="1.0" ?>
<robot name="bbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Math constants -->
  <xacro:property name="math_pi" value="3.141592653589793" />  

  <!-- Math macros -->
  <xacro:macro name="box_inertial" params="mass x y z">  
    <inertial>
      <mass value="${mass}" />
      <inertia 
        ixx="${mass * (y * y + z * z) / 12.0}" ixy="0.0" ixz="0.0"
        iyy="${mass * (z * z + x * x) / 12.0}" iyz="0.0"
        izz="${mass * (x * x + y * y) / 12.0}" />
    </inertial>
  </xacro:macro>  

  <!-- Constants for robot dimensions -->
  <xacro:property name="hull_mass" value="20000.0" />
  <xacro:property name="hull_loa" value="10.0" />  
  <xacro:property name="hull_woa" value="4.0" />  
  <xacro:property name="hull_doa" value="2.0" />  
  <xacro:property name="camera_mass" value="0.1" />  
  <xacro:property name="camera_size" value="0.1" />  

  <!-- Import Gazebo elements -->
  <xacro:include filename="$(find bbot_description)/urdf/bbot.gazebo" />

  <!-- Import materials -->
  <xacro:include filename="$(find bbot_description)/urdf/materials.xacro" />

  <!-- Base link (main hull) -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${hull_loa} ${hull_woa} ${hull_doa}"/>
      </geometry>
      <material name="orange" />
    </visual>

    <collision>
      <geometry>
        <box size="${hull_loa} ${hull_woa} ${hull_doa}"/>
      </geometry>
    </collision>
    
    <xacro:box_inertial mass="${hull_mass}" x="${hull_loa}" y="${hull_loa}" z="${hull_doa}" />
  </link>

  <!-- Camera -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
      <material name="black" />
    </visual>

    <collision>
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
    </collision>
    
    <xacro:box_inertial mass="${camera_mass}" x="${camera_size}" y="${camera_size}" z="${camera_size}" />
  </link>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${hull_loa/2 - 0.25} 0 ${hull_doa/2 + camera_size/2}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>


</robot>